[FIX] Manifesto do Destinatário
erpbrasil/erpbrasil.edoc pull request #34
Opened 2021-05-16 22:22 UTC by mileo

2021-05-18 14:52 UTC, gabrielcardoso21 approved these changes

2021-05-18 15:09 UTC, luismalta approved these changes

2021-05-18 16:03 UTC, marcelsavegnago approved these changes
LGTM

2021-05-20 08:05 UTC, rvalyi requested changes

2021-05-20 08:05 UTC, rvalyi commented on src/erpbrasil/edoc/mde.py
> +            #xml_object = retEnvConfRecebto.parseString(xml_assinado)
faltou um espaço aqui pro flake8 ficar feliz: https://travis-ci.org/github/erpbrasil/erpbrasil.edoc/jobs/771491913#L296

2021-05-20 12:20 UTC, merged