Adicionado validação do xml.
erpbrasil/erpbrasil.edoc pull request #42
Opened 2021-12-24 16:44 UTC by crsilveira

2022-01-16 21:03 UTC, netosjb commented
Não é o mesmo que a PR #37 ?

2022-01-24 11:34 UTC, crsilveira commented
Só mudei a mensagem de erro, tentei deixar ela mais transparente para o usuário.

2022-01-24 15:14 UTC, marcelsavegnago commented
> @crsilveira não tenho certeza, mas talvez o mais correto é revisar e sugerir a alteração na PR #37 que já está em aberto.

@rvalyi oq acha ?

2022-02-22 10:38 UTC, renatonlima requested changes
Olá @crsilveira,

Eu havia implementado no nfellib a validação do schema https://github.com/akretion/nfelib/commit/c5865a50c818d3025737a7e26c1c2470a2ccb8b6#diff-ab2d865f73b83f88956effb9a9506783b6dd92cf3c8c3056ea5daee57ac3b27cR45 que é um método que ao passar o arquivo XML ele retorna uma lista com as mensagens de erro o que restaria apenas implementar no Odoo a leitura dessas mensagens.

2022-02-22 11:39 UTC, crsilveira commented
Olá Renato, 

Correto, então não precisamos do que foi feito acima.

2022-06-23 11:17 UTC, closed without merging