[FIX] regex
erpbrasil/erpbrasil.edoc pull request #81
Opened 2024-07-10 21:23 UTC by corredato

2024-07-10 21:23 UTC, mileo approved these changes

2024-07-10 22:34 UTC, antoniospneto commented
@corredato consegue arrumar a verão da nfelib para os testes rodarem e conferir se vai passar em tudo?

2024-07-10 23:39 UTC, mileo commented
> nfelib

A nfelib não aceita todas as versões do python mais.

2024-07-10 23:40 UTC, mileo commented
@corredato pode colocar algo explicativo log caso o match não obtenha algo, para nunca mais cairmos nesse problema de ficar horas procurando o problema.

2024-07-10 23:44 UTC, antoniospneto commented
> > nfelib
> 
> A nfelib não aceita todas as versões do python mais.

Mas ai podemos remover as versões do python não suportadas dos testes, precisamos ver se os testes estão passando pra saber se houve alguma regressão.

2024-07-10 23:46 UTC, antoniospneto requested changes
é bom verificar se os testes estão passando, para evitar regressão.

2024-07-11 00:22 UTC, rvalyi commented
eu removi o Python 3.7 recentemente da nfelib pois ele ja ta end of life faz mais de 1 ano (e agora vem o EOL do 3.8 alias)...
Se for um problema pode usar a nfelib 2.0.7 ainda, mas as lib downstream precisam evoluir tb, nao da para lib downstream obrigar o upstream a travar no tempo...

2024-07-11 00:25 UTC, antoniospneto commented
@corredato  @mileo 

Tenho receio de que essa alteração possa quebrar a comunicação com outros webservices. Analisando melhor, acho que precisamos tornar o regex mais genérico para lidar com os diferentes prefixos que podem aparecer no body.

Sugiro utilizar algo mais genérico como:

```python
pattern = r'<[a-zA-Z0-9:]*Body.*?>(.*?)</[a-zA-Z0-9:]*Body>
match = re.search(pattern, retorno.text.replace("\n", ""))
```

Acredito que essa abordagem seja mais robusta e evitará problemas com prefixos variados nos webservices. Além disso, outras pessoas já enfrentaram problemas semelhantes, como podemos ver nas seguintes referências:

- https://github.com/erpbrasil/erpbrasil.edoc/issues/55
- https://github.com/erpbrasil/erpbrasil.edoc/pull/47
- https://github.com/erpbrasil/erpbrasil.edoc/pull/50/files

2024-07-11 17:31 UTC, corredato commented
@antoniospneto Testei a emissão de nfce e nfe com esse pattern genérico e funcionou, já commitei, obrigado.

2024-07-11 20:13 UTC, antoniospneto commented
@corredato ver o pre-commit que não tá passando? tbm arrumar os testes? tem que travar a nfelib na versão 2.0.7

2024-07-17 00:18 UTC, antoniospneto approved these changes

2024-07-18 12:55 UTC, mileo approved these changes

2024-07-18 20:44 UTC, mileo commented
> @mileo vc tinha marcado como rascunho, tá tudo certo agora?

Sim! Agora tá ok!

2024-07-19 12:49 UTC, merged